"""add legal_capacity

Revision ID: 0f577fe4fe9c
Revises: f473e210fa7d
Create Date: 2026-02-17 18:20:15.144860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f577fe4fe9c'
down_revision: Union[str, Sequence[str], None] = 'f473e210fa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dining_rooms', sa.Column('legal_capacity', sa.Integer(), nullable=False))
    op.alter_column('dining_rooms', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_dining_rooms_name'), table_name='dining_rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dining_rooms_name'), 'dining_rooms', ['name'], unique=True)
    op.alter_column('dining_rooms', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('dining_rooms', 'legal_capacity')
    # ### end Alembic commands ###
