"""fixed op.drop.constraint autogenerate bug

Revision ID: 3db4f6a43069
Revises: 225ab4d255df
Create Date: 2026-02-17 16:32:07.728177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db4f6a43069'
down_revision: Union[str, Sequence[str], None] = '225ab4d255df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_attendees', sa.Column('seat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reservation_attendees_seat_id'), 'reservation_attendees', ['seat_id'], unique=False)
    op.create_foreign_key(None, 'reservation_attendees', 'seats', ['seat_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation_attendees', type_='foreignkey')
    op.drop_index(op.f('ix_reservation_attendees_seat_id'), table_name='reservation_attendees')
    op.drop_column('reservation_attendees', 'seat_id')
    # ### end Alembic commands ###
