"""add fired_at to reservations

Revision ID: caa7572df155
Revises: d8332a6b13bc
Create Date: 2026-02-18 12:59:33.118274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'caa7572df155'
down_revision: Union[str, Sequence[str], None] = 'd8332a6b13bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_items_reservation_attendee_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'reservation_attendees', ['reservation_attendee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reservation_attendees', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('reservation_attendees', 'dietary_restrictions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_unique_constraint('uq_res_seat', 'reservation_attendees', ['reservation_id', 'seat_id'])
    op.drop_column('reservation_attendees', 'metadata')
    op.add_column('reservations', sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'fired_at')
    op.add_column('reservation_attendees', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('uq_res_seat', 'reservation_attendees', type_='unique')
    op.alter_column('reservation_attendees', 'dietary_restrictions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('reservation_attendees', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_reservation_attendee_id_fkey'), 'order_items', 'reservation_attendees', ['reservation_attendee_id'], ['id'])
    # ### end Alembic commands ###
