"""initial_clean_schema

Revision ID: d78e7afd14a3
Revises: 
Create Date: 2026-02-19 08:34:43.186504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd78e7afd14a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('membership_status', sa.String(length=30), nullable=False),
    sa.Column('guest_allowance', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('member','staff','admin')", name=op.f('ck_users_ck_users_role')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_users_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_by_user_id'), 'users', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_type'), 'activity_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('audit_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_trails_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_trails'))
    )
    op.create_index(op.f('ix_audit_trails_created_at'), 'audit_trails', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_trails_operation'), 'audit_trails', ['operation'], unique=False)
    op.create_index(op.f('ix_audit_trails_record_id'), 'audit_trails', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_trails_table_name'), 'audit_trails', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_trails_user_id'), 'audit_trails', ['user_id'], unique=False)
    op.create_table('dining_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('legal_capacity', sa.Integer(), server_default='100', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_dining_rooms_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_dining_rooms_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dining_rooms'))
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('relation', sa.String(length=60), nullable=True),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_members_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('dietary_tags', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_menu_items_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_menu_items_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items'))
    )
    op.create_index(op.f('ix_menu_items_category'), 'menu_items', ['category'], unique=False)
    op.create_index(op.f('ix_menu_items_is_available'), 'menu_items', ['is_available'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('email_to', sa.String(length=255), nullable=True),
    sa.Column('email_from', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('amount_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applies_to', sa.String(length=50), nullable=True),
    sa.Column('min_party_size', sa.Integer(), nullable=True),
    sa.Column('max_party_size', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_taxable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('min_party_size <= max_party_size', name=op.f('ck_rules_ck_rule_party_size_range')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_rules_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_rules_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_index(op.f('ix_rules_rule_type'), 'rules', ['rule_type'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_system_settings_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('dining_room_id', sa.Integer(), nullable=True),
    sa.Column('total_reservations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirmed_reservations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancelled_reservations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('no_show_reservations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_guests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_party_size', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('food_revenue', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('cover_charge_revenue', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('service_fee_revenue', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_collected', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('gratuity_collected', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_table_capacity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tables_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('utilization_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('breakfast_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lunch_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dinner_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('brunch_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('top_menu_items', sa.JSON(), nullable=True),
    sa.Column('peak_hour', sa.String(length=20), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dining_room_id'], ['dining_rooms.id'], name=op.f('fk_daily_stats_dining_room_id_dining_rooms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_stats')),
    sa.UniqueConstraint('stat_date', 'dining_room_id', name='uq_daily_stat_date_room')
    )
    op.create_index(op.f('ix_daily_stats_dining_room_id'), 'daily_stats', ['dining_room_id'], unique=False)
    op.create_index(op.f('ix_daily_stats_stat_date'), 'daily_stats', ['stat_date'], unique=False)
    op.create_table('table_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dining_room_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_table_entities_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['dining_room_id'], ['dining_rooms.id'], name=op.f('fk_table_entities_dining_room_id_dining_rooms')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_table_entities_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_entities')),
    sa.UniqueConstraint('dining_room_id', 'table_number', name='uq_dining_room_table_number')
    )
    op.create_index(op.f('ix_table_entities_dining_room_id'), 'table_entities', ['dining_room_id'], unique=False)
    op.create_index(op.f('ix_table_entities_table_number'), 'table_entities', ['table_number'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dining_room_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_reservations_cancelled_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_reservations_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['dining_room_id'], ['dining_rooms.id'], name=op.f('fk_reservations_dining_room_id_dining_rooms')),
    sa.ForeignKeyConstraint(['table_id'], ['table_entities.id'], name=op.f('fk_reservations_table_id_table_entities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reservations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_index(op.f('ix_reservations_date'), 'reservations', ['date'], unique=False)
    op.create_index(op.f('ix_reservations_dining_room_id'), 'reservations', ['dining_room_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_table_id'), 'reservations', ['table_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_seats_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['table_id'], ['table_entities.id'], name=op.f('fk_seats_table_id_table_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_seats_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('table_id', 'seat_number', name='uq_seat_table_seat_number')
    )
    op.create_index(op.f('ix_seats_table_id'), 'seats', ['table_id'], unique=False)
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('applied_to_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fees_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_fees_reservation_id_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_fees_rule_id_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fees'))
    )
    op.create_index(op.f('ix_fees_reservation_id'), 'fees', ['reservation_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='incomplete', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_orders_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('reservation_id', name=op.f('uq_orders_reservation_id'))
    )
    op.create_table('reservation_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('attendee_type', sa.String(length=20), server_default='guest', nullable=False),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_reservation_attendees_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_reservation_attendees_member_id_members')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reservation_attendees_reservation_id_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_reservation_attendees_seat_id_seats'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_attendees'))
    )
    op.create_index(op.f('ix_reservation_attendees_member_id'), 'reservation_attendees', ['member_id'], unique=False)
    op.create_index(op.f('ix_reservation_attendees_reservation_id'), 'reservation_attendees', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_reservation_attendees_seat_id'), 'reservation_attendees', ['seat_id'], unique=False)
    op.create_table('reservation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), server_default='text', nullable=False),
    sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['reservation_messages.id'], name=op.f('fk_reservation_messages_parent_message_id_reservation_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reservation_messages_reservation_id_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_reservation_messages_sender_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_messages'))
    )
    op.create_index(op.f('ix_reservation_messages_created_at'), 'reservation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_reservation_messages_reservation_id'), 'reservation_messages', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_reservation_messages_sender_user_id'), 'reservation_messages', ['sender_user_id'], unique=False)
    op.create_table('reservation_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('food_subtotal', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('cover_charges', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('service_fees', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('subtotal_before_tax', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('subtotal_after_tax', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('gratuity_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('gratuity_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('payment_status', sa.String(length=20), server_default='unpaid', nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculated_by_user_id'], ['users.id'], name=op.f('fk_reservation_totals_calculated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reservation_totals_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_totals'))
    )
    op.create_index(op.f('ix_reservation_totals_reservation_id'), 'reservation_totals', ['reservation_id'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('reservation_attendee_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_order_items_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_attendee_id'], ['reservation_attendees.id'], name=op.f('fk_order_items_reservation_attendee_id_reservation_attendees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_menu_item_id'), 'order_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_reservation_attendee_id'), 'order_items', ['reservation_attendee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_reservation_attendee_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_menu_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_reservation_totals_reservation_id'), table_name='reservation_totals')
    op.drop_table('reservation_totals')
    op.drop_index(op.f('ix_reservation_messages_sender_user_id'), table_name='reservation_messages')
    op.drop_index(op.f('ix_reservation_messages_reservation_id'), table_name='reservation_messages')
    op.drop_index(op.f('ix_reservation_messages_created_at'), table_name='reservation_messages')
    op.drop_table('reservation_messages')
    op.drop_index(op.f('ix_reservation_attendees_seat_id'), table_name='reservation_attendees')
    op.drop_index(op.f('ix_reservation_attendees_reservation_id'), table_name='reservation_attendees')
    op.drop_index(op.f('ix_reservation_attendees_member_id'), table_name='reservation_attendees')
    op.drop_table('reservation_attendees')
    op.drop_table('orders')
    op.drop_index(op.f('ix_fees_reservation_id'), table_name='fees')
    op.drop_table('fees')
    op.drop_index(op.f('ix_seats_table_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_table_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_dining_room_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_date'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_table_entities_table_number'), table_name='table_entities')
    op.drop_index(op.f('ix_table_entities_dining_room_id'), table_name='table_entities')
    op.drop_table('table_entities')
    op.drop_index(op.f('ix_daily_stats_stat_date'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_dining_room_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_rules_rule_type'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_menu_items_is_available'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_table('members')
    op.drop_table('dining_rooms')
    op.drop_index(op.f('ix_audit_trails_user_id'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_table_name'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_record_id'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_operation'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_created_at'), table_name='audit_trails')
    op.drop_table('audit_trails')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_resource_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
